name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      working-directory: php/8.1/debian
      run: docker build . --file Dockerfile --tag baseartifacts.azurecr.io/php:8.1-latest

    - uses: azure/docker-login@v1
      with:
        login-server: baseartifacts.azurecr.io
        username: ${{ secrets.ARM_CLIENT_ID }}
        password: ${{ secrets.ARM_CLIENT_SECRET }}
    - run: |
        docker pull baseartifacts.azurecr.io/php:8.1-stable || true
        docker pull php:8.1
        DIGEST1=$(docker images --no-trunc --quiet baseartifacts.azurecr.io/php:8.1-stable)
        DIGEST2=$(docker images --no-trunc --quiet php:8.1)
        echo "DIGEST1="$DIGEST1
        echo "DIGEST2="$DIGEST2
        if [ "$DIGEST1" != "$DIGEST2" ]; then
          echo DIFF DETECTED PUSHING
          docker rmi baseartifacts.azurecr.io/php:8.1-stable
          docker tag php:8.1 baseartifacts.azurecr.io/php:8.1-stable
          docker push baseartifacts.azurecr.io/php:8.1-stable
          echo PUSHED
        else
          echo NO UPDATE found for php:8.1
        fi
